// src/main/java/com/qaassist/agent/mr/MrDescriptionGenerator.java
package com.qaassist.agent.mr;

import com.qaassist.domain.artifact.TestSuite;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

@Slf4j
@Component
public class MrDescriptionGenerator {

  /**
   * Генерирует структурированное Markdown-описание для Merge Request.
   */
  public String generate(TestSuite suite, String metricsJson) {
    return """
            ## 🤖 QA Assist: Автоматически сгенерированные автотесты
            
            📌 **User Story**: `%s`
            📂 **Suite**: `%s`
            🏷️ **Tags**: `api`, `ui`, `auto-generated`, `qa-assist`
            
            ---
            
            ### 📊 Метрики генерации
            - ✅ Тест-кейсов: `%d`
            - 🧩 Шагов: `%d`
            - ⚙️ Техники ISTQB: `%s`
            
            ### 📦 Структура изменений
            ```
            src/test/java/
            ├── api/          # REST Assured тесты
            ├── ui/           # Playwright Java тесты
            │   └── pages/    # Page Object классы
            └── BaseTest.java # Базовая конфигурация
            ```
            
            ### 🔗 Связанные артефакты
            - 📋 Jira: `%s`
            - 📈 Zephyr: _(кейсы загружены автоматически)_
            - 📐 Coverage Report: _(будет доступен после CI run)_
            
            > 💡 Этот MR создан автоматически агентом `MrCreator`. 
            > Проверьте сгенерированные локаторы и эндпоинты перед мёрджем.
            > При необходимости запустите `mvn clean test` локально.
            
            ---
            *Generated by QA Assistance AI Framework v1.0*
            """.formatted(
        suite.sourceStoryId(),
        suite.suiteName(),
        suite.testCases().size(),
        suite.totalSteps(),
        String.join(", ", suite.metadata().appliedTechniques()),
        suite.sourceStoryId()
    );
  }
}