// src/main/java/com/qaassist/agent/mr/TestProjectPackager.java
package com.qaassist.agent.mr;

import com.qaassist.agent.api.ApiTestGenerator.GeneratedApiTest;
import com.qaassist.agent.ui.UiAutomationSkill;
import com.qaassist.agent.mr.model.CommitFile;
import com.qaassist.domain.artifact.TestSuite;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Slf4j
@Component
@RequiredArgsConstructor
public class TestProjectPackager {

  /**
   * Упаковывает сгенерированные тесты в готовый к запуску Maven-проект.
   */
  public List<CommitFile> packageProject(TestSuite suite,
      List<GeneratedApiTest> apiTests,
      List<UiAutomationSkill.GeneratedUiTest> uiTests) {
    List<CommitFile> files = new ArrayList<>();
    String basePackage = "com.qaassist.tests";

    // 1. pom.xml (базовый для REST Assured + Playwright)
    files.add(new CommitFile("pom.xml", generatePomXml(basePackage)));

    // 2. Базовый тестовый конфигурационный класс
    files.add(new CommitFile("src/test/java/" + basePackage.replace('.', '/') + "/BaseTest.java", generateBaseTest()));

    // 3. API тесты
    for (GeneratedApiTest api : apiTests) {
      String path = "src/test/java/" + basePackage.replace('.', '/') + "/api/" + api.className() + ".java";
      files.add(new CommitFile(path, api.sourceCode()));
    }

    // 4. UI тесты + Page Objects
    for (UiAutomationSkill.GeneratedUiTest ui : uiTests) {
      String pagePath = "src/test/java/" + basePackage.replace('.', '/') + "/ui/pages/" + ui.pageClassName() + ".java";
      files.add(new CommitFile(pagePath, ui.pageSource()));

      String testPath = "src/test/java/" + basePackage.replace('.', '/') + "/ui/" + ui.testClassName() + ".java";
      files.add(new CommitFile(testPath, ui.testSource()));
    }

    // 5. README с инструкциями
    files.add(new CommitFile("README.md", generateReadme(suite)));

    log.info("📦 Packaged {} files for suite: {}", files.size(), suite.suiteName());
    return files;
  }

  private String generatePomXml(String pkg) {
    return """
            <?xml version="1.0" encoding="UTF-8"?>
            <project xmlns="http://maven.apache.org/POM/4.0.0"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                <modelVersion>4.0.0</modelVersion>
                <groupId>%s</groupId>
                <artifactId>qa-auto-tests</artifactId>
                <version>1.0-SNAPSHOT</version>
                <properties>
                    <maven.compiler.source>17</maven.compiler.source>
                    <maven.compiler.target>17</maven.compiler.target>
                </properties>
                <dependencies>
                    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><version>5.10.2</version><scope>test</scope></dependency>
                    <dependency><groupId>io.rest-assured</groupId><artifactId>rest-assured</artifactId><version>5.4.0</version><scope>test</scope></dependency>
                    <dependency><groupId>com.microsoft.playwright</groupId><artifactId>playwright</artifactId><version>1.44.0</version><scope>test</scope></dependency>
                    <dependency><groupId>org.assertj</groupId><artifactId>assertj-core</artifactId><version>3.25.3</version><scope>test</scope></dependency>
                </dependencies>
                <build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-surefire-plugin</artifactId><version>3.2.5</version></plugin></plugins></build>
            </project>
            """.formatted(pkg);
  }

  private String generateBaseTest() {
    return """
            package %s;
            
            import io.restassured.RestAssured;
            import org.junit.jupiter.api.BeforeAll;
            
            public abstract class BaseTest {
                @BeforeAll
                static void setup() {
                    RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
                }
            }
            """.formatted("com.qaassist.tests");
  }

  private String generateReadme(TestSuite suite) {
    return """
            # 🤖 QA Assist: Auto-Generated Tests
            
            **Suite**: `%s`
            **Story**: `%s`
            **Generated At**: `%s`
            
            ## 🚀 How to run
            ```bash
            mvn clean test
            # or specific tags
            mvn test -Dgroups=api
            mvn test -Dgroups=ui
            ```
            
            ## 📊 Coverage
            - Total Cases: %d
            - Total Steps: %d
            
            Generated by QA Assistance AI Framework.
            """.formatted(suite.suiteName(), suite.sourceStoryId(),
        suite.generatedAt(), suite.testCases().size(), suite.totalSteps());
  }
}